### PR TITLE
Add support for OID 1.2.840.10045.2.1

### PR DESCRIPTION
**Pull request by gilbertbw**
Based on this http://oid-info.com/get/1.2.840.10045.2.1 page I believe the OID
1.2.840.10045.2.1 represents Elliptic curve public key cryptography.

### CODE REVIEW

**Comment by ralphje** [comment]
Can you confirm you have seen this used? As it seems that it is not a signature algorithm, rather a keytype.

**Comment by gilbertbw** [comment]
Hi @ralphje, sorry for the late reply. I had missed this comment.

Yes, I have seen this, when doing something like this:  
```python
with exe_path.open("rb") as f:
    pefile = SignedPEFile(f)
    for signed_data in pefile.signed_datas:
        valid_to = signed_data.certificates[0].valid_to
```

with this one of our installers, e.g. https://www.talkjcs.com/installer/jcs/31.102.09/JCSInstall.exe

I am not that familiar with PKI, but the patch I wrote seems to work for us. We are only using the `valid_to`, as above, so I may have broken something else.

**Comment by ralphje** [comment]
I have verified that this is indeed the correct location, I was mistaken.

**Comment by gilbertbw** [comment]
Thanks

**Pull request closed without merging**
